# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Program\Python_code\PyQT5_final_project\designer_ui\menu_toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 954, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuoption1 = QtWidgets.QMenu(self.menuBar)
        self.menuoption1.setObjectName("menuoption1")
        self.menuoption2 = QtWidgets.QMenu(self.menuBar)
        self.menuoption2.setObjectName("menuoption2")
        self.menuoption3 = QtWidgets.QMenu(self.menuBar)
        self.menuoption3.setObjectName("menuoption3")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionoption1_2 = QtWidgets.QAction(MainWindow)
        self.actionoption1_2.setObjectName("actionoption1_2")
        self.actionoption2 = QtWidgets.QAction(MainWindow)
        self.actionoption2.setObjectName("actionoption2")
        self.actionoption1_4 = QtWidgets.QAction(MainWindow)
        self.actionoption1_4.setObjectName("actionoption1_4")
        self.menuoption1.addAction(self.actionoption1_2)
        self.menuoption1.addAction(self.actionoption2)
        self.menuoption1.addSeparator()
        self.menuoption1.addAction(self.actionoption1_4)
        self.menuBar.addAction(self.menuoption1.menuAction())
        self.menuBar.addAction(self.menuoption2.menuAction())
        self.menuBar.addAction(self.menuoption3.menuAction())
        self.toolBar.addAction(self.actionoption1_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionoption2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionoption1_4)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuoption1.setTitle(_translate("MainWindow", "New"))
        self.menuoption2.setTitle(_translate("MainWindow", "option2"))
        self.menuoption3.setTitle(_translate("MainWindow", "option3"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionoption1_2.setText(_translate("MainWindow", "Open233"))
        self.actionoption1_2.setShortcut(_translate("MainWindow", "A"))
        self.actionoption2.setText(_translate("MainWindow", "Close"))
        self.actionoption1_4.setText(_translate("MainWindow", "Exit"))
